import type { Metadata } from 'next';
import Link from 'next/link';
import { FiArrowLeft } from 'react-icons/fi';
import { Footer, Header } from '@/components/landing';

export const metadata: Metadata = { title: 'Terms of Service | Bluely', description: 'The terms that guide use of the Bluely platform.' };

const terms = [
    ['01', 'Using Bluely', 'By creating an account or using Bluely, you agree to these Terms. You must provide accurate information, keep your account secure and use the service lawfully.'],
    ['02', 'What Bluely is', 'Bluely helps people log health information, understand patterns and access educational and community experiences. Features may change as the service develops.'],
    ['03', 'Medical boundaries', 'Bluely is not a medical device and does not provide medical advice, diagnosis or treatment. Predictions and insights are informational only. Never use Bluely to decide insulin doses, change medication or handle an emergency. Speak with a qualified healthcare professional for medical decisions.'],
    ['04', 'Your information', 'You retain ownership of the information you enter. You give Bluely permission to store and process it to provide the service, generate requested insights and operate the platform. See the Privacy Policy for more detail.'],
    ['05', 'Stories and community', 'Public story submissions are reviewed by the Bluely team and are not automatically published. If we would like to feature an experience, we will contact the person first. Please do not submit urgent medical information through public forms.'],
    ['06', 'Service availability', 'Bluely is provided as available. We may maintain, update, pause or change features as we improve the service. We aim to communicate meaningful changes clearly.'],
    ['07', 'Ending an account', 'You may stop using Bluely or request account deletion. We may suspend access when an account is used to compromise the service, other people or these Terms.'],
    ['08', 'Contact', 'Questions about these Terms can be sent to support@bluely.health. These Terms are governed by the laws of the Republic of Cameroon, subject to applicable law.'],
];

export default function TermsPage() {
    return <div className="min-h-screen bg-[#f6f8ff] text-[#172853]"><Header /><main className="mx-auto max-w-360 px-5 pb-24 pt-10 sm:px-8 sm:pt-16 lg:px-10"><Link href="/" className="inline-flex items-center gap-2 text-sm font-bold text-[#1F2F98] hover:text-[#17257d] focus-visible:outline-2 focus-visible:outline-[#1F2F98]"><FiArrowLeft aria-hidden="true" /> Back to Bluely</Link><section className="mt-12 bg-[#132653] px-6 py-14 text-white sm:px-12 sm:py-20 lg:px-20 lg:py-24"><p className="text-xs font-bold tracking-[0.19em] text-[#b9cbff] sm:text-sm">A SHARED UNDERSTANDING</p><h1 className="mt-5 max-w-190 text-[clamp(3rem,6vw,6.5rem)] font-semibold leading-none tracking-[-0.07em]">The terms behind the work.</h1><div className="mt-8 flex flex-col gap-6 border-t border-white/20 pt-6 text-sm leading-7 text-[#d6def2] sm:flex-row sm:justify-between sm:gap-12"><p>Terms of Service</p><p>Last updated: September 28, 2026</p></div></section><section className="mt-8 bg-white px-6 py-10 sm:px-10 sm:py-14 lg:ml-[8%] lg:mr-[4%] lg:px-16 lg:py-16"><p className="max-w-190 text-lg leading-8 text-[#52617d] sm:text-xl">Bluely is being built around trust. These terms explain what the platform is for, what it cannot do and the responsibilities we share while using it.</p><div className="mt-14 border-t border-[#cbd5ed]">{terms.map(([number, title, text]) => <article key={number} className="grid gap-5 border-b border-[#dbe3f3] py-8 lg:grid-cols-[100px_minmax(0,1fr)] lg:gap-12"><p className="text-sm font-bold tracking-[0.14em] text-[#1F2F98]">{number}</p><div><h2 className="text-2xl font-semibold tracking-[-0.035em] sm:text-3xl">{title}</h2><p className="mt-4 max-w-180 text-base leading-7 text-[#52617d]">{text}</p></div></article>)}</div><div className="mt-12 flex flex-wrap gap-6 border-t-2 border-[#1F2F98] pt-6 text-sm font-bold"><Link href="/privacy" className="text-[#1F2F98] underline underline-offset-4">Read Privacy &amp; Data Protection</Link><Link href="/contact" className="text-[#1F2F98] underline underline-offset-4">Contact Bluely</Link></div></section></main><Footer /></div>;
}
